### PR TITLE
Port To Python 3

### PR DESCRIPTION
**Pull request by Creatune**
As the sugargame repo was already updated I didn't get any errors regarding that. I ported the other files to python 3 (it wasn't much). But while testing, when I click on the sound/microphone button on the top left of the activity, it gives an AttributeError. It gave the same error before porting as well. Please let me know if there is anything I can do about this. Thank you :)

### CODE REVIEW

**Comment by Creatune** [comment]
Also, it is giving an "UnboundLocalError: local variable 'event' referenced before assignment" both before and after porting. I tried to fix it but to no avail, so can you please help me out with this?

**Comment by srevinsaju** [comment]
> Also, it is giving an "UnboundLocalError: local variable 'event' referenced before assignment" both before and after porting. I tried to fix it but to no avail, so can you please help me out with this?

@Creatune can you give the error message?

Tested, logs contains:
```
ALSA lib pcm.c 8526 : (sn_pcm_recover) underrun occurred
```

**Comment by quozl** [comment]
@Creatune, please don't report already known issues?  :grin:  Read both https://github.com/sugarlabs/flappy/issues/22 and https://github.com/sugarlabs/flappy/issues/21 for comments on the error.  Known issues and any open pull requests must be checked before porting.  See _making sure the activity works properly before porting_ in the porting guide.

**Comment by quozl** [comment]
Also, if the sound button doesn't work, please fix it or create an issue if you won't fix it.

**Pull request merged**
